#!/bin/bash
# Stop current instance of rpimonitor
kill -9 $(ps -C rpimonitord -o pid= | perl -ne 'chomp and print "$_ "') > /dev/null 2>&1
# keep configuration in case of upgrade (for version 2.x < 2.7 on raspbian only)
if [ -d /etc/rpimonitord.conf.d/ ]; then
  cp -a /etc/rpimonitord.conf.d/* /etc/rpimonitor/
  mv /etc/rpimonitor/default.conf /etc/rpimonitor/template/raspbian.conf
  sed -i "/\/usr\/share\/rpimonitor\/updatestatus.txt/\/var\/lib\/rpimonitor\/updatestatus.txt/" /etc/rpimonitor/template/raspbian.conf
  mv -f /etc/rpimonitord.conf /etc/rpimonitor/daemon.conf
  rm -fr /etc/rpimonitord.conf.d/
fi
# keep graph history in case of upgrade (for version 2.x < 2.7 on raspbian only)
if [ -d /usr/share/rpimonitor/web/stat/ ]; then
  if [ ! -L /usr/share/rpimonitor/web/stat ]; then
    mkdir -p /usr/lib/rpimonitor
    mv /usr/share/rpimonitor/web/stat/ /var/lib/rpimonitor/
  fi
fi
# setup configuration base on target distribution
distrib=$(cat /etc/os-release | perl -ne '/^NAME="(\S+)/ and print lc($1)')
touch  /etc/rpimonitor/data.conf
rm  /etc/rpimonitor/data.conf
if [ -f /etc/rpimonitor/template/$distrib.conf ]; then
  ln -s /etc/rpimonitor/template/${distrib}.conf /etc/rpimonitor/data.conf
else
  ln -s /etc/rpimonitor/template/raspbian.conf /etc/rpimonitor/data.conf
fi
#Change cron right
chmod 600 /etc/cron.d/rpimonitor
# reinstall the service
update-rc.d -f rpimonitor remove
update-rc.d -f rpimonitor defaults
# start RPi-Monitor
/etc/init.d/rpimonitor start
